language: go
env:
  GO111MODULE=on
deploy:
  provider: heroku
  api_key:
    secure: "e4Nb/7aa/y32IE7VIhnkrhkfVf7xeTwXzH1BDfeOfroya8wgL835+qfD7Yog4KcsXJkz2hjaE6ctpUabvH4GTXS9szOkzDqlyfscMBbpfSlY+sEvphOq3Wdt4lJhnE2vT4+WUF5EgI52IGOyZceI8ar/iAh5/JapVkFyL95mr+MkhTazjADlPrLpcXqrefYpctaoXKmpLGB2jLKBpnSD1dtUmwBGakMNvZtL1zNmTvj6W5n2Neb9c8j5ClD2OBR8W7QCOGjP4DQ637COamwV+ffQjhfCZdX2YKk0fSfXmpJbFW1iXOdWRXXwmHlFESd8ZfiTWeLZQwndV06gyurx1lZg/6W498KT9Zq46D/Sl/Vae1mWYarHqXJSZd8FbZ88lncnmfwxkWWKMgjgvN86RcQyc3bBWpkmEtIQrSq/zVuqkQMhwSC+eAfkta3P4vaOPEzlW7W7zD3EO24Q/GGYi7P2uR2v1Kf1A7wz1gSzwBC19Cnbl5s6pSYZq+yzN6gS0v6B+wvLQPhbEBV5TYpT+7P9sT54/EpYxr90Qgl0uaSSLbOYn1ynIRfnt73NDAJhgt6Ujr/5X2I6zoikKnWdiAN2YdUsyLudFjGPeE5dA4qvCHh2ExZLC024oCyk1ZU2l0En/JarJoioH13zrT4saijTDAgdEzZBTs7wUblp/Os="
  app:
    probando: golang-pokemon-api