language: go
env:
  GO111MODULE=on
deploy:
  provider: heroku
  api_key:
    secure: "Ldm5o7jRYc4G6Uu8VMftI6/708OHlwcdircsizs2jk8PfBF/Q8M0Ud48iDQYRigLXtRGOBVc03+Sw64qlUPSb70h2vI/tqyrtrtMxPSGbWHxQMDgWyLNZPqAJZCuBV/pkK1XZIbWUWkB6eLT/JoIsT5H1uotdqz00qEksfhY7eWvp14uEDcujoezbYg/Pif+Wcgp8fKk5vcJP30MHv3RjLX6tEsiTWoSi8qj3Yp/NfdcMe2Q88bqa6AOMOdL1cq+YiTsj/kUR3LTr1Jx5SHbMWSqxRRvcl9W/Rw7dkgildN/3E0MyfxtrFCpY12fRw8C97pyz9IfOCvsIByiAZ603VQfMLvEGK9g4whzQ4OsqynhMv5ttwlzx55+4n9KPbBCeIg4GO7r2DziShWHRzS66ZbLqQXUuCtbVRGL7+6dyx1NWjUK6pjcVBJVYeK/hQMCjCRuLp73XmkJLr6t0GPZKjoBWUj8PNHvuwJH2HdGq/ZFLyxYBhoadSYo80snbL1qJIIE/3k/R61ElE0j9JhLk9AAA9d7niYlQRi11GndZ/Gr1vb4YcwhNmHhOz3s4ar22G60OYKjGhglmzf63bbMRVw2fVHBHb9vpLq6bcf1FyuPPwT9O6iVlaDLb1uN9fg/7eNX2cJSjvMLVDVqIW3CQl2q7uxQZIL42jyB5WDlvFY="
  app:
    probando: golang-pokemon-api