language: go
env:
  GO111MODULE=on
deploy:
  provider: heroku
  api_key:
    secure: "eK4F7v5ufSMWTq2fnGgYvKjTrOaVDzq9xER0AhJ/cLwl0deSGp9UpbBK2mM9OKp0z0f03IHGxRsQbF77qVPyYbkROcuzzLOxXGRGBz+XBI8Hruzpv8EScJCU4B1GOAdjUsOKZ5jmMWUIKYhlEOFZTP4yzi8rx19SmeLenKtZgxPjFmlfwyNROi3GhC8Kylnq0+sMw7yg6wr75AtcoAidyf0a8IQruhjjSv+b7ytMV0vdM5HpEF8oM13/daGOYnEQ9YF3msboNL45GTzcyNx00t7mUuPxg/lewMg3SYKORhvXrzfJniCyy3NvEEinJpVBbDNZFv1CvMIdfX7nm49T9BC70ep8+mwpuloN82zf3xa5euwnAkQ1fqXMs8eZE0UVmfdJPbgO8bPT+92hPDoSvAr8cnfggMCA0PmIXZiU5qqw3gTH3VIvmbS8yd3SEDvueowPwb7tekmqfkpWHJk0dkZCvh1SaUpKztKvLyxM4YVfun+jc/4+WMoIS3XZ6EWuVyoI0flI0oqwHA685hZ15zp8RPjYm3RR5EEHPtQ0K6JVED90LqkBiKHZYTruYO/gWMUXFpn/wLB0/mz4x0DGCTKxJs2EBcHcoLdyFTjguso0P6EEd3bjJMiFgNQsJ6FFkz5i0rahWccym/l+A4XRWafdHJeRbGfrKmUwVrFoOfU="
  app:
    golang-pokemon-api/probando