language: go
env:
  GO111MODULE=on
deploy:
  provider: heroku
  api_key:
    secure: "A2xxyo0rhhxZEiCbGcUKFAd90V5suqMFw4Svg/E5PJgd5W0mY3NxY2hEb3dVBkGcYBZsQ1i35xWdUnQmjpPO2eF6kkjX/w1RPXSqNNT8zKWUMUeKmDGjXY1/axxHJp01LdQuEw3sn9JQZqeMzBw9C1nB5IZGwOu4zCffVSAQ42beDpl2Z0KFZe588JOQmIhvjCyo2qKtstLKOiCLthVekspUQVsIpSYA1oHy56RzkOOg0O3mZ4lXk5zgVeu2gPgOiLCleJ8RoLrmYCOeSj2nefvh99sasld2KwKWD0GrIw9XRZXDwz7hpg92+OzGRaRVN4DnM//GxrhGbfb1TdjDuZGkeHPRHAF/V55ngvmW3rJYzgoVSQLcnf4hBo1ilkG2SQnP1doKjxr73YeZ5u2sUmawMFMjSDnnMDp5mvMkTOqfAweTFolZRbCu67lwSaDDTekWj4kikPVDr8czF7VTdG26lZV9lcaoQg673anyY9dIvCt9qnY/z0JuGqIfHutF3qr7tYMddfv+p1Jj2GEq5F5HbpQ964+lm8thNVA2hNWiRr+DGuYVaMzZBgENx1vACsqusXJHVVvN0RnfrgRQjt2hQ/unwb1355oNcEz6NgoJ5fIb/r17hI1w5V9yaj1Sdy1cH2Iis6p8qlbEz6lJpZVbeiHFCDLYMnn8EhvceiY="
  app:
    master: golang-pokemon-api