language: go
env:
  GO111MODULE=on
deploy:
  provider: heroku
  api_key:
    secure: "qZT/022ONDFhVMh5ByDwvoURJbtl1NCWnqJ3LvVrKd4h1AqOXzRTByfZ8GuifJZO6j6IVkTccS0uk4ssfOQpLZWAyL1UVi0F+ZsbhiA5MKQyFTnVMhxHysmS6IMLGXYI7T+L68aH10vCh6sCAqFoxRfdb3lP8Dmm0Hjmk/wFTPJqY8LpP7tBKPz+408TMH875gDDBTVoNDiA1HNXKMRR2Vzbx+9oMNIl1pMKLzgftkrBjlt2Ml1PMok3TNHtHzY2+4L17xsKGcZaiZuAUE91hdDw7tP9sTxHA6wBU0JzL2zaC9k1VIhf6RrYp0kEGLR3StLY1RlIaMD5I9nC47/4AsFVgCG2B1mSO5xuOM3SCGBptlfuAL289IrjDOgloHooSMWYbzDYjI1LWnfDjQJx9RYE7mB79cyauyG6dV/YoP2yYVMr+Pzjkklal0ypFuZuOSY7TIFgHB4TFMEseRjAlVr3aqJH5JEP+8Zy3epGXWWW2gU4BrKxVa8SXK8AVTkMpzAVGT5OI+P5sGuXiO7hMrbg88WbtcyUDSeWQLXV/a19l6ER+QbG9WgiHCc00ykJ5Adwf890lAXFreftpNvu1i9Kpy8MTk5cZfrR4aJ0gUeIHbSQp5f8FODxNV/z0oNb+Hu83WG5b6PTJ+/aiRrt7rovMdOqE7ZofgTJGbY1hq8="
  app:
    probando: golang-pokemon-api